//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1291387.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int orderId { get; set; }
        public int clientId { get; set; }
        public int productId { get; set; }
    
        public virtual client client { get; set; }
        public virtual product product { get; set; }
    }
}
